---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_storage_software.html
keywords: storage, software, flexpod, express, ontap, e, series, santricity
summary: The storage operating systems listed in this section are supported in the FlexPod Express platform.
---

= Storage Software
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.578185
//

FlexPod Express supports storage systems that run NetApp ONTAP or SANtricity operating systems.

== NetApp ONTAP

The NetApp ONTAP software is the operating system that runs on AFF and FAS storage systems. ONTAP provides a highly scalable storage architecture that enables nondisruptive operations, nondisruptive upgrades, and an agile data infrastructure.

For more information about ONTAP, see the http://www.netapp.com/us/products/platform-os/ontap/index.aspx[ONTAP product page^].

== E-Series SANtricity software

E-Series SANtricity software is the operating system that runs on E-Series storage systems. SANtricity provides a highly flexible system that meets varying application needs and offers built-in high availability and a wide variety of data protection features.

For more information, see the http://www.netapp.com/us/products/platform-os/santricity/index.aspx[SANtricity product page^].
