---
sidebar: sidebar
permalink: ehr-epic-sizing/ehr-epic-sizing_additional_information.html
keywords: additional, information, flexpod, epic, sizing
summary: To learn more about the information that is described in this document, see the following documents or websites.
---

= Additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:05:29.262582
//

[.lead]
To learn more about the information that is described in this document, see the following documents or websites:

* FlexPod Datacenter with FC Cisco Validated Design. Detailed deployment of FlexPod Datacenter environment.
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html[https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html^]

* TR-3928: NetApp Best Practices for Epic. Overview of Epic software environments, reference architectures, and integration best practices guidance.
+
https://fieldportal.netapp.com/?oparams=68646[https://fieldportal.netapp.com/?oparams=68646^]

* TR-3930i: NetApp Sizing Guidelines for Epic (access to Field Portal is required to view this document)
+
https://fieldportal.netapp.com/?oparams=68786[https://fieldportal.netapp.com/?oparams=68786^]

* Epic_on_Cisco_UCS_tech_brief. Cisco Best practices with Epic on Cisco UCS.
+
https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf[https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf^]

* NetApp https://netapp-my.sharepoint.com/:w:/p/dorianh/ETSsgHnsIipGkSvMd-EZFpEBIvAmw_rAZvw1RGDtWiMr8w[FlexPod^] Design Zone
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html[https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html^]

* FlexPod DC with Fibre Channel Storage (MDS Switches) Using NetApp AFF, vSphere 6.5U1, and Cisco UCS Manager
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html[https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html^]

* TR-4693: FlexPod Datacenter for Epic EHR Deployment Guide
+
https://www.netapp.com/us/media/tr-4693.pdf[https://www.netapp.com/us/media/tr-4693.pdf^]

* NetApp Product Documentation
+
https://www.netapp.com/us/documentation/index.aspx[https://www.netapp.com/us/documentation/index.aspx^]
