---
sidebar: sidebar
permalink: healthcare/ehr-epic-performance_introduction.html
keywords: flexpod, epic, performance, testing, healthcare, workloads, hardware, configuration, cisco, unified, computing, system
summary: The objective of this report is to highlight the performance of FlexPod with NetApp All Flash A300 and A700 storage systems with Epic Healthcare workloads.
---

= TR-4784: FlexPod for Epic Performance Testing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:41:30.086926
//


Brian O’Mahony,
Ganesh Kamath
Atul Bhalodia
Brandon Agee

== Objective

The objective of this report is to highlight the performance of FlexPod with NetApp All Flash A300 and A700 storage systems with Epic Healthcare workloads.

=== Epic Hardware configuration guide

For acceptable end-user performance, Epic production and disaster recovery operational database (ODB) target- read and target- write time requirements are as follows:

* For randomly placed reads to database files measured at the system call level:
** Average read latencies must be 2ms or less
** 99% of read latencies must be below 60ms
** 99.9% of read latencies must be below 200ms
** 99.99% of read latencies must be below 600ms
* For randomly placed writes to database files measured at the system call level:
** Average write latencies must be 1ms or less depending on size

[NOTE]
These requirements change with time. Epic prepares a customer- specific Epic Hardware Configuration Guide (HCG). Refer to your HCG for details on requirements.

== Overall solution benefits

By running an Epic environment on a FlexPod architectural foundation, healthcare organizations can see an improvement in staff productivity and a decrease in capital and operating expenses. FlexPod Datacenter with Epic delivers several benefits specific to the healthcare industry:

* *Simplified operations and lowered costs.* Eliminate the expense and complexity of legacy proprietary RISC/UNIX platforms by replacing them with a more efficient and scalable shared resource capable of supporting clinicians wherever they are. This solution delivers higher resource utilization for greater ROI.
* *Quicker deployment of infrastructure.* Whether it’s in an existing data center or in a remote location, the integrated and tested design of FlexPod Datacenter with Epic enables customers to have new infrastructure up and running in less time with less effort.
* *Scale-out architecture.* Scale SAN and NAS from terabytes to tens of petabytes without reconfiguring running applications.
* *Nondisruptive operations.* Perform storage maintenance, hardware lifecycle operations, and software upgrades without interrupting business operations.
* *Secure multitenancy.* FlexPod supports the needs of shared virtualized server and storage infrastructure, enabling secure multitenancy of facility-specific information, particularly if you are hosting multiple instances of databases and software.
* *Pooled resource optimization.* FlexPod can help reduce physical server and storage controller counts and load- balance workload demands. It can also boost utilization while improving performance.
* *Quality of service (QoS).* FlexPod offers QoS on the entire stack. Industry-leading QoS storage policies enable differentiated service levels in a shared environment. These policies enable optimal performance for workloads and help isolate and control runaway applications.
* *Storage efficiency.* Reduce storage costs with the NetApp 7:1 storage efficiency guarantee.
* *Agility.* The industry-leading workflow automation, orchestration, and management tools offered by FlexPod systems allow IT to be far more responsive to business requests. These business requests can range from Epic backup and provisioning of additional test and training environments to analytics database replications for population health management initiatives.
* *Productivity.* Quickly deploy and scale this solution for optimal clinician end-user experiences.
* *Data Fabric.* The NetApp Data Fabric architecture weaves data together across sites, beyond physical boundaries, and across applications. The NetApp Data Fabric is built for data-driven enterprises in a data-centric world. Data is created and used in multiple locations, and it often must be leveraged and shared with other locations, applications, and infrastructures. Customers want a way to manage data that is consistent and integrated. It provides a way to manage data that puts IT in control and simplifies ever-increasing IT complexity.

== Cisco Unified Computing System, Cisco Nexus and MDS Switching, and ONTAP all-flash storage

The FlexPod for Epic Healthcare delivers the performance, efficiency, manageability, scalability, and data protection that IT organizations need to meet for the most stringent Epic requirements. By accelerating Epic production database performance and by reducing application deployment time from months to weeks, FlexPod helps organizations maximize the potential of their Epic investment.

=== Cisco Unified Computing System

As a self-integrating, self-aware system, Cisco Unified Computing System (UCS) consists of a single management domain interconnected with a unified I/O infrastructure. The Cisco UCS for Epic environments has been aligned with Epic infrastructure recommendations and best practices to help make sure that infrastructure can deliver critical patient information with maximum availability.

The foundation of Epic on the Cisco UCS architecture is Cisco UCS technology with its integrated systems management, Intel Xeon processors, and server virtualization. These integrated technologies solve data- center challenges and enable you to meet your goals for data- center design for Epic. Cisco UCS unifies LAN, SAN, and systems management into one simplified link for rack servers, blade servers, and virtual machines. The Cisco UCS is an end-to-end I/O architecture that incorporates Cisco Unified Fabric and Cisco fabric extender (FEX) technology to connect every component in the Cisco UCS with a single network fabric and a single network layer.

The system is designed as a single virtual blade chassis that incorporates and scales across multiple blade chassis. The system implements a radically simplified architecture that eliminates the multiple redundant devices that populate traditional blade server chassis and result in layers of complexity. Examples include Ethernet switches, Fibre Channel switches, and chassis management modules. The Cisco UCS contains a redundant pair of Cisco fabric interconnects that provide a single point of management and a single point of control for all I/O traffic.

The Cisco UCS uses service profiles to help ensure that virtual servers in the UCS infrastructure are configured correctly. Service profiles include critical server information about the server identity such as LAN and SAN addressing, I/O configurations, firmware versions, boot order, network VLAN, physical port, and quality-of-service (QoS) policies. Service profiles can be dynamically created and associated with any physical server in the system within minutes rather than within hours or days. The association of service profiles with physical servers is performed as a single, simple operation that enables migration of identities between servers in the environment without any physical configuration changes. It facilitates rapid bare-metal provisioning of replacements for failed servers.

Using service profiles helps to ensure that servers are configured consistently throughout the enterprise. When using multiple Cisco UCS management domains, UCS Central can use global service profiles to synchronize configuration and policy information across domains. If maintenance is required in one domain, the virtual infrastructure can be migrated to another domain. Therefore, applications continue to run with high availability even when a single domain is offline.

Cisco UCS has been extensively tested with Epic over a multiyear period to demonstrate that it meets server configuration requirements. Cisco UCS is a supported server platform, as listed in customers’ “Epic Hardware Configuration Guide.”

=== Cisco Nexus and Cisco MDS Ethernet and Fibre Channel switching

Cisco Nexus switches and MDS multilayer directors provide enterprise-class connectivity and SAN consolidation. Cisco multiprotocol storage networking reduces business risk by providing flexibility and options. Supported protocols include Fibre Channel (FC), Fibre Connection (FICON), FC over Ethernet (FCoE), SCSI over IP (iSCSI), and FC over IP (FCIP).

Cisco Nexus switches offer one of the most comprehensive data- center- network feature sets in a single platform. They deliver high performance and density for both the data center and the campus core. They also offer a full feature set for data- center aggregation, end-of-row deployments, and data center interconnect deployments in a highly resilient, modular platform.

The Cisco UCS integrates computing resources with Cisco Nexus switches and a unified I/O fabric that identifies and handles different types of network traffic, including storage I/O, streamed desktop traffic, management, and access to clinical and business applications.

In summary, the Cisco UCS provides the following important advantages for Epic deployments:

* *Infrastructure scalability.* Virtualization, efficient power and cooling, cloud scale with automation, high density, and performance all support efficient data- center growth.
* *Operational continuity.* The design integrates hardware, NX-OS software features, and management to support zero-downtime environments.
* *Transport flexibility.* Incrementally adopt new networking technologies with a cost-effective solution.

Together, Cisco UCS with Cisco Nexus switches and MDS multilayer directors provide a compelling computer, networking, and SAN connectivity solution for Epic.

=== NetApp all-flash storage systems

NetApp AFF systems address enterprise storage requirements with high performance, superior flexibility, and best-in-class data management. Built on ONTAP data management software, AFF systems speed up your business without compromising the efficiency, reliability, or flexibility of your IT operations. With enterprise-grade all-flash arrays, AFF systems accelerate, manage, and protect your business-critical data and enable an easy and risk-free transition to flash media for your data center.

Designed specifically for flash, AFF A-series all-flash systems deliver industry-leading performance, capacity, density, scalability, security, and network connectivity in a dense form factor. With the addition of a new entry-level system, the new AFF A- series family extends enterprise-grade flash to midsize businesses. At up to seven million IOPS per cluster with sub- millisecond latency, the AFF A series is the fastest family of all-flash arrays, built on a true unified scale-out architecture.

With the AFF A series, you can complete twice the work at half the latency relative to the previous generation of AFF systems. The members of the AFF A series are the industry’s first all-flash arrays that provide both 40Gb Ethernet (40GbE) and 32Gb Fibre Channel (FC) connectivity. Therefore, they eliminate the bandwidth bottlenecks that are increasingly moving from storage to the network as flash becomes faster and faster.

NetApp has taken the lead for all-flash storage innovations with the latest solid-state-drive (SSD) technologies. As the first all-flash array to support 15TB SSDs, AFF systems, with the introduction of the A series, also become the first to use multistream write SSDs. Multistream write capability significantly increases the usable capacity of SSDs.

NetApp ONTAP Flash Essentials is the power behind the performance of All Flash FAS. ONTAP is industry-leading data management software. However, it is not widely known that ONTAP, with its NetApp WAFL (Write Anywhere File Layout) file system, is natively optimized for flash media.

ONTAP Flash Essentials optimizes SSD performance and endurance with the following features, among others:

* NetApp data-reduction technologies, including inline compression, inline deduplication, and inline data compaction, can provide significant space savings. Savings can be further increased by using NetApp Snapshot and NetApp FlexClone technologies. Studies based on customer deployments have shown that these data-reduction technologies have enabled space savings of up to 933 times.
* Coalesced writes to free blocks maximize performance and flash media longevity.
* Flash-specific read-path optimizations provide consistent low latency.
* Parallelized processing handles more requests at once.
* Software-defined access to flash maximizes deployment flexibility.
* Advanced Disk Partitioning (ADP) increases storage efficiency and further increases usable capacity by almost 20%.
* The Data Fabric enables live workload migration between flash and hard-disk-drive tiers on the premises or to the cloud.

QoS capability guarantees minimum service-level objectives in multiworkload and multitenant environments.

The key differentiators with adaptive QOS are as follows:

* Simple self-managing IOPS/TB or throughput MB/TB. Performance grows as data capacity grows.
* Simplified consumption of storage based on service- level performance policies.
* Consolidation of mixed workloads onto a single cluster with guaranteed performance service levels. No more silos are required for critical applications.
* Major cost saving by consolidating nodes and disk.
