---
sidebar: sidebar
permalink: healthcare/ehr-epic-sizing_technical_specifications_for_small,_medium,_and_large_architectures.html
keywords: technical, specifications, architecture, components, software, epic
summary: The FlexPod design enables a flexible infrastructure that encompasses many different components and software versions.
---

= Technical specifications for small, medium, and large Architectures
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:05:29.245686
//

The FlexPod design enables a flexible infrastructure that encompasses many different components and software versions. Use https://fieldportal.netapp.com/content/443847[TR-4036: FlexPod Technical Specifications^] as a guide for building or assembling a valid FlexPod configuration. The configurations that are detailed are only the minimum requirements for FlexPod, and they are just a sample. They can be expanded in the included product families as required for different environments and use cases.

The following table lists the capacity configurations for the Epic production database workload. The total capacity listed accommodates the need for all Epic components.

|===
| |Small |Medium |Large

|Platform
|One AFF A300 HA pair
|One AFF A300 HA pair
|One AFF A300 HA pair
|Disk shelves
|24 x 3.8TB
|48 x 3.8TB
|96 x 3.8TB
|Epic database size
|3 to 20TB
|20TB-40TB
|>40TB
|Total IOPS
|22,000
|50,000
|125,000
|Raw
|92.16TB
|184.32TB
|368.64TB
|Usable capacity
|65.02TiB
|134.36TiB
|269.51TiB
|Effective capacity (2:1 storage efficiency)
|130.04TiB
|268.71TiB
|539.03TiB
|===

Epic production workloads can be easily satisfied with a single AFF A300 HA pair. An AFF A300 HA pair can push upward of 200k IOPs, which satisfies a large Epic deployment with room for more shared workloads.

Some customer environments might have multiple Epic production workloads running simultaneously, or they might simply have higher IOP requirements. In that case, work with the NetApp account team to size the storage systems according to the required IOPs and capacity and arrive at the right platform to serve the workloads. There are customers running multiple Epic environments on an AFF A700 HA pair.

The following table lists the standard software required for the small, medium, and large configurations.

|===
|Software |Product family |Version or release

|Storage
|Data ONTAP
|ONTAP 9.3 GA
.3+|Network
|Cisco UCS-FI
|Cisco UCS Manager 3.2(2f)
|Cisco Ethernet switches
|7.0(3)I7(2)
|Cisco FC: Cisco MDS 9132T
|8.2(2)
.2+|Hypervisor
|Hypervisor
|VMware vSphere ESXi 6.5 U1
|VMs
|RHEL 7.4
.4+|Management
|Hypervisor management system
|VMware vCenter Server 6.5 U1 (VCSA)
|NetApp Virtual Storage Console
|VSC 7.0P1
|SnapCenter
|SnapCenter 4.0
|Cisco UCS Manager
|3.2(2f) or later
|===

The following table lists small configuration infrastructure components.

|===
|Layer |Product family |Quantity and model |Details

.4+|Compute
|Cisco UCS 5108 Chassis
|Two
|Based on the number of blades required to support the users
|Cisco UCS blade servers
|4 x B200 M5
|Each with 2 x 18 cores, 2.7GHz, and 384GB
BIOS 3.2(2f)
|Cisco UCS VIC
|4 x UCS 1340
|VMware ESXi fNIC FC driver: 1.6.0.34
VMware ESXi eNIC Ethernet driver: 1.0.6.0
(see the matrix)
|2 x Cisco UCS FI
|6332-16UP with Cisco UCS Manager 3.2 (2f)
|
|Network
|Cisco Ethernet switches
|
|2 x Cisco Nexus 93180YC-FX
.2+|Storage network
|IP network N9k for BLOB storage
|
|FI and UCS chassis
|FC: Cisco MDS 9132T
|
|Two Cisco 9132T switches
.3+|Storage
|NetApp AFF A300
|1 HA pair
|1 x 2-node cluster
|DS224C disk shelf
|1 DS224C disk shelf (fully populated with 24 drives)
|One fully populated disk shelf
|SSD
|24 x 3.8TB
|
|===

A single disk shelf of 3.8TB SSD drives should suffice for most smaller Epic customer deployments. However, for shared workloads, more disk capacity might be required. You must size for your capacity accordingly.

The following table lists the medium configuration infrastructure components.

|===
|Layer |Product family |Quantity and model |Details

.4+|Compute
|Cisco UCS 5108 Chassis
|Four
|Based on the number of blades required to support the users
|Cisco UCS blade servers
|4 x B200 M5
|Each with 2 x 18 cores, 2.7GHz/3.0Ghz, and 384GB
4 sockets for Cache DB
BIOS 3.2(2f)
|Cisco UCS VIC
|4 x UCS 1340
|VMware ESXi fNIC FC driver: 1.6.0.34
VMware ESXi eNIC Ethernet driver: 1.0.6.0
(see the matrix)
|2 x Cisco UCS FI
|6332-16UP with Cisco UCS Manager 3.2(2f)
|
|Network
|Cisco Ethernet switches
|
|2 x Cisco Nexus 93180YC-FX
.2+|Storage network
|IP network: Cisco N9k for BLOB storage
|
|FI and Cisco UCS chassis
|FC: Cisco MDS 9132T
|
|Two Cisco 9132T switches
.3+|Storage
|NetApp AFF A300
|2 HA pairs
|2 x 2-node cluster for all Epic workloads (Production, Report, Clarity, VMware, Citrix, CIFS, and so on)
|DS224C disk shelf
|2 x DS224C disk shelves
|2 fully populated disk shelves
|SSD
|48 x 3.8TB
|
|===

Four disk shelves of 3.8TB SSD drives should suffice for almost all medium Epic customer deployments. However, assess your disk capacity requirements and size for required capacity accordingly.

The following table lists the large configuration infrastructure components.

|===
|Layer |Product family |Quantity and model |Details

.4+|Compute
|Cisco UCS 5108 Chassis
|8
|
|Cisco UCS blade servers
|4 x B200 M5
|Each with 2 x 24 cores, 2.7GHz, and 576GB
BIOS 3.2(2f)
|Cisco UCS VIC
|4 x UCS 1340
|VMware ESXi fNIC FC driver: 1.6.0.34
VMware ESXi eNIC Ethernet driver: 1.0.6.0
(see the matrix)
|2 x Cisco UCS FI
|6332-16UP with Cisco UCS Manager 3.2(2f)
|
|Network
|Cisco Ethernet switches
|
|2 x Cisco Nexus 93180YC-FX
.2+|Storage network
|IP network: Cisco N9k for BLOB storage
|
|
|FC: Cisco MDS 9706
|
|Two Cisco 9706 switches
.3+|Storage
|NetApp AFF A300
|3 HA pairs
|3 x 2-node cluster for Epic workloads (Prod, Report, Clarity, VMware, Citrix, CIFS, and so on)
|DS224C disk shelf
|4 x DS224C disk shelves
|4 fully populated disk shelves
|SSD
|96 x 3.8TB
|
|===

Some customer environments might have multiple Epic production workloads running simultaneously, or they might simply have higher IOPS requirements. In such cases, work with the NetApp account team to size the storage systems according to the required IOPS and capacity and determine the right platform to serve the workloads. There are customers running multiple Epic environments on an AFF A700 HA pair.
