---
sidebar: sidebar
permalink: healthcare/ehr-epic-performance_conclusion.html
keywords: flash, storage, epic, array, pools, adaptive, qos, performance
summary: By 2020, all Epic customers must be on flash storage. NetApp ONTAP was the first all- flash array to get a high- comfort rating from Epic, and it is listed under Enterprise Storage Arrays. All NetApp platforms that run a GA version of ONTAP are high comfort.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:41:30.117431
//

By 2020, all Epic customers must be on flash storage. NetApp ONTAP was the first all- flash array to get a high- comfort rating from Epic, and it is listed under Enterprise Storage Arrays. All NetApp platforms that run a GA version of ONTAP are high comfort.

Epic requires that critical workloads like Production, Report, and Clarity are physically separated on storage allocations called pools. NetApp provides multiple pools of storage in a single cluster with each node and offers a simplified single cluster and single OS for the entire Epic solution. ONTAP supports all protocols for NAS and SAN, with mixed tiers of storage for SSD, HDD, and cloud.

The introduction of Adaptive QoS in ONTAP 9.3, with significant enhancements in ONTAP 9.4, allows for the creation of storage pools with software without the need for physical separation. This capability greatly simplifies architecture development, permits the consolidation of nodes and disks, and improves performance for critical workloads like production by spreading across nodes. It also eliminates storage performance issues caused by bullies and guarantees consistent performance for the life of the workload.
