---
sidebar: sidebar
permalink: ehr-epic-performance/ehr-epic-performance_additional_information.html
keywords: additional, information, flexpod, epic, performance, testing
summary: To learn more about the information that is described in this document, see the following documents or websites.
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:41:30.119602
//

To learn more about the information that is described in this document, see the following documents or websites:

== FlexPod Design Zone

* NetApp FlexPod Design Zone
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html[https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html^]

* FlexPod DC with FC Storage (MDS Switches) Using NetApp AFF, vSphere 6.5U1, and Cisco UCS Manager
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html[https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html^]

* Cisco Best Practices with Epic on Cisco UCS
+
https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf[https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf^]

== NetApp technical reports

* TR-4693: FlexPod Datacenter for Epic EHR Deployment Guide
+
https://www.netapp.com/us/media/tr-4693.pdf[https://www.netapp.com/us/media/tr-4693.pdf^]

* TR-4707: FlexPod for Epic Directional Sizing Guide
+
https://www.netapp.com/us/media/tr-4707.pdf[https://www.netapp.com/us/media/tr-4707.pdf^]

* https://fieldportal.netapp.com/content/192896[TR-3929: Reallocate Best Practices Guide^]
+
https://www.netapp.com/us/media/tr-3929.pdf

* TR-3987: Snap Creator Framework Plug-In for InterSystems Caché
+
https://www.netapp.com/us/media/tr-3987.pdf

* TR-3928: NetApp Best Practices for Epic
+
https://www.netapp.com/us/media/tr-3928.pdf[https://www.netapp.com/us/media/tr-3928.pdf^]

* TR-4017: FC SAN Best Practices
+
https://www.netapp.com/us/media/tr-4017.pdf[https://www.netapp.com/us/media/tr-4017.pdf^]

* TR-3446: SnapMirror Async Overview and Best Practices Guide
+
https://www.netapp.com/us/media/tr-3446.pdf[https://www.netapp.com/us/media/tr-3446.pdf^]

== ONTAP documentation

* NetApp product documentation
+
https://www.netapp.com/us/documentation/index.aspx[https://www.netapp.com/us/documentation/index.aspx^]

* Virtual Storage Console (VSC) for vSphere documentation
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048[https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048^]

* ONTAP 9 Documentation Center
+
http://docs.netapp.com/ontap-9/index.jsp[http://docs.netapp.com/ontap-9/index.jsp^]

== Cisco Nexus, MDS, Cisco UCS, and Cisco UCS Manager guides

* Cisco UCS Servers Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html^]

* Cisco UCS Blade Servers Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html^]

* Cisco UCS B200 M5 Datasheet
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html^]

* Cisco UCS Manager Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html^]

* Cisco UCS Manager 3.2(3a) Infrastructure Bundle (requires Cisco.com authorization)
+
https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529[https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529^]

* Cisco Nexus 9300 Platform Switches
+
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html^]

* Cisco MDS 9148S FC Switch
+
https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html[https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html^]
