---
sidebar: sidebar
permalink: ehr-epic-performance/ehr-epic-performance_executive_summary.html
keywords: epic, performance, storage, efficiency, all, flash, fas, platform, ehr
summary: To showcase the storage efficiency and performance of NetApp’s All Flash FAS platform, NetApp performed a study to measure Epic EHR performance on AFF A300 and AFF A700 systems.
---

= Executive Summary
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:41:30.095471
//

To showcase the storage efficiency and performance of NetApp’s All Flash FAS platform, NetApp performed a study to measure Epic EHR performance on AFF A300 and AFF A700 systems. NetApp measured the data throughput, peak IOPS, and average latency of an AFF A300 running ONTAP 9.5 and an AFF A700 storage controller running ONTAP 9.4, each running an Epic EHR workload. In a manner similar to SPC-3 testing, all inline storage efficiency features were enabled.

We ran the Epic GenIO workload generator on an AFF A300 cluster that contained a total of twenty-four 3.8TB SSDs and on an AFF A700 cluster that contained a total of forty-eight 3.8TB SSDs. We tested our cluster at a range of load points that drove the storage to peak CPU utilization. At each load point, we collected information about the storage IOPS and latency.

NetApp has consistently with each software upgrade improved performance in the range of 40-50%. Innovation with performance enhancements has varied based on workload and protocol.

The Epic performance test demonstrated that the AFF A300 cluster IOPS increased from 75,000 IOPS at <1ms to a peak performance of 188,929 IOPS at <1ms. For all load points at or below 200,000 IOPS, we were able to maintain consistent storage latencies of no greater than 1ms. Additionally, the Epic performance test demonstrated that the AFF A700 cluster IOPS increased from 75,000 IOPS at <1ms to a peak performance of 319,000 IOPS at <1ms. For all load points at or below 320,000 IOPS, we were able to maintain consistent storage latencies of no greater than 1ms.
