---
sidebar: sidebar
permalink: fp-express-tech-spec/fp-express-tech-spec_storage_software.html
keywords: storage, software, flexpod, express, ontap, e, series, santricity
summary: The storage software listed in this section are supported in the FlexPod Express platform.
---

= Storage Software
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.578185
//

The storage software listed in this section are supported in the FlexPod Express platform.

== NetApp ONTAP

The NetApp ONTAP software is installed on every NetApp storage system.

FlexPod is validated with ONTAP providing a highly scalable storage architecture that enables nondisruptive operations, nondisruptive upgrades, and an agile data infrastructure. For more information about ONTAP, see the http://www.netapp.com/us/products/platform-os/ontap/index.aspx[ONTAP Data Management Software product page^].

== E-Series SANtricity software

E-Series SANtricity software is the OS that runs on every E-Series storage system. SANtricity provides a highly flexible system that meets varying application needs and offers built-in high availability and a wide variety of data protection features. For more information, see the http://www.netapp.com/us/products/platform-os/santricity/index.aspx[SANtricity Software product site^].
